# Generated by Django 5.2.15 on 2026-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=50)),
                ('severite', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], db_index=True, default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('statut', models.CharField(choices=[('OPEN', 'Ouvert'), ('RESOLVED', 'Traité')], db_index=True, default='OPEN', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOANS', 'Suspension temporaire des emprunts'), ('ACCOUNT', 'Blocage du compte'), ('WARNING', 'Avertissement formel')], max_length=10)),
                ('motif', models.TextField()),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
    ]
