# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abuse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportabus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_abus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapportabus',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abus_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restriction',
            name='appliquee_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions_appliquees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restriction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rapportabus',
            index=models.Index(fields=['client', 'statut'], name='abus_client_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportabus',
            index=models.Index(fields=['severite', 'statut'], name='abus_severite_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='restriction',
            index=models.Index(fields=['client', 'active', 'fin'], name='restriction_client_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='restriction',
            constraint=models.CheckConstraint(condition=models.Q(('fin__isnull', True), ('fin__gt', models.F('debut')), _connector='OR'), name='restriction_fin_apres_debut'),
        ),
    ]
