"""Catalogue illustré livré avec les interfaces d'origine du projet."""

CATALOGUE_DEMO = [
    {
        "titre": "Le Petit Prince",
        "auteur": "Antoine de Saint-Exupéry",
        "categorie": "Roman jeunesse",
        "isbn": "9782070612758",
        "annee": 1943,
        "editeur": "Gallimard",
        "poids": 210,
        "stock": 3,
        "couverture": "petit-prince.webp",
        "description": "Un aviateur rencontre dans le désert un jeune voyageur venu d'une autre planète. Ce conte poétique interroge l'amitié, la responsabilité et le regard porté sur le monde.",
    },
    {
        "titre": "L'Étranger",
        "auteur": "Albert Camus",
        "categorie": "Philosophie",
        "isbn": "9782070360024",
        "annee": 1942,
        "editeur": "Gallimard",
        "poids": 185,
        "stock": 2,
        "couverture": "etranger.webp",
        "description": "À travers le regard détaché de Meursault, Albert Camus explore l'absurde, la solitude et le rapport de l'individu aux normes sociales.",
    },
    {
        "titre": "Les Misérables",
        "auteur": "Victor Hugo",
        "categorie": "Classique",
        "isbn": "9782253006312",
        "annee": 1862,
        "editeur": "Le Livre de Poche",
        "poids": 720,
        "stock": 4,
        "couverture": "les-miserables.jpg",
        "description": "Les destins de Jean Valjean, Cosette, Fantine et Marius se croisent dans une fresque sociale consacrée à la justice, la misère et la rédemption.",
    },
    {
        "titre": "L'Alchimiste",
        "auteur": "Paulo Coelho",
        "categorie": "Aventure",
        "isbn": "9782290004449",
        "annee": 1988,
        "editeur": "J'ai lu",
        "poids": 190,
        "stock": 3,
        "couverture": "alchimiste.webp",
        "description": "Santiago, jeune berger andalou, part à la recherche d'un trésor. Son voyage devient une quête intérieure sur le courage et l'accomplissement de sa légende personnelle.",
    },
    {
        "titre": "1984",
        "auteur": "George Orwell",
        "categorie": "Dystopie",
        "isbn": "9782070368228",
        "annee": 1949,
        "editeur": "Gallimard",
        "poids": 340,
        "stock": 3,
        "couverture": "1984.jpg",
        "description": "Dans un monde dominé par la surveillance et la manipulation du langage, Winston Smith tente de préserver une part de vérité et de liberté.",
    },
    {
        "titre": "Orgueil et Préjugés",
        "auteur": "Jane Austen",
        "categorie": "Classique",
        "isbn": "9782253004356",
        "annee": 1813,
        "editeur": "Le Livre de Poche",
        "poids": 360,
        "stock": 2,
        "couverture": "orgueil-et-prejuges.jpg",
        "description": "Elizabeth Bennet observe les codes sociaux de son époque tandis que sa relation avec Darcy révèle les effets de l'orgueil, des préjugés et de la première impression.",
    },
    {
        "titre": "Crime et Châtiment",
        "auteur": "Fiodor Dostoïevski",
        "categorie": "Psychologie",
        "isbn": "9782253082507",
        "annee": 1866,
        "editeur": "Le Livre de Poche",
        "poids": 610,
        "stock": 2,
        "couverture": "crime-et-chatiment.jpg",
        "description": "Après avoir commis un crime au nom d'une théorie morale, Raskolnikov affronte la culpabilité, la fièvre intérieure et la possibilité du repentir.",
    },
    {
        "titre": "Le Nom de la Rose",
        "auteur": "Umberto Eco",
        "categorie": "Mystère historique",
        "isbn": "9782253033134",
        "annee": 1980,
        "editeur": "Le Livre de Poche",
        "poids": 570,
        "stock": 2,
        "couverture": "le-nom-de-la-rose.jpg",
        "description": "Dans une abbaye médiévale, Guillaume de Baskerville enquête sur une série de morts mystérieuses liées à une bibliothèque interdite.",
    },
    {
        "titre": "Kafka sur le rivage",
        "auteur": "Haruki Murakami",
        "categorie": "Contemporain",
        "isbn": "9782264053718",
        "annee": 2002,
        "editeur": "10/18",
        "poids": 480,
        "stock": 3,
        "couverture": "kafka-sur-le-rivage.webp",
        "description": "Un adolescent en fuite et un vieil homme singulier avancent dans deux récits parallèles où le réel glisse vers le rêve, la mémoire et les symboles.",
    },
    {
        "titre": "Dune",
        "auteur": "Frank Herbert",
        "categorie": "Science-fiction",
        "isbn": "9780441172719",
        "annee": 1965,
        "editeur": "Ace Books",
        "poids": 620,
        "stock": 4,
        "couverture": "dune.jpg",
        "description": "Sur la planète désertique Arrakis, Paul Atréides se trouve au cœur d'une lutte politique, écologique et spirituelle autour de la ressource la plus précieuse de l'univers.",
    },
    {
        "titre": "Sapiens",
        "auteur": "Yuval Noah Harari",
        "categorie": "Histoire",
        "isbn": "9780062316097",
        "annee": 2011,
        "editeur": "Harper",
        "poids": 520,
        "stock": 3,
        "couverture": "sapiens.jpg",
        "description": "Une synthèse accessible de l'histoire de l'humanité, de l'apparition d'Homo sapiens aux transformations scientifiques, politiques et économiques modernes.",
    },
    {
        "titre": "Atomic Habits",
        "auteur": "James Clear",
        "categorie": "Développement personnel",
        "isbn": "9780735211292",
        "annee": 2018,
        "editeur": "Avery",
        "poids": 390,
        "stock": 3,
        "couverture": "atomic-habits.jpg",
        "description": "Une méthode pratique pour construire de bonnes habitudes, éliminer les comportements nuisibles et progresser durablement grâce à de petits changements quotidiens.",
    },
]
