# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LATE', 'Retard'), ('DAMAGE', 'Dommage'), ('LOSS', 'Perte'), ('OTHER', 'Autre')], max_length=10)),
                ('motif', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('OPEN', 'Ouverte'), ('PAID', 'Réglée'), ('CANCELLED', 'Annulée')], db_index=True, default='OPEN', max_length=10)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('reglee_le', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalites', to=settings.AUTH_USER_MODEL)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalites_creees', to=settings.AUTH_USER_MODEL)),
                ('emprunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalites', to='loans.emprunt')),
            ],
            options={
                'ordering': ['-creee_le'],
                'indexes': [models.Index(fields=['client', 'statut'], name='penalite_client_statut_idx'), models.Index(fields=['type', 'statut'], name='penalite_type_statut_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gte', 0)), name='penalite_montant_positif'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'PAID'), _negated=True), ('reglee_le__isnull', False), _connector='OR'), name='penalite_reglee_datee')],
            },
        ),
    ]
