# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('CONVERTED', 'Convertie en emprunt'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée'), ('REFUSED', 'Refusée')], db_index=True, default='ACTIVE', max_length=12)),
                ('reservee_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(db_index=True)),
                ('annulee_le', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.CharField(blank=True, max_length=250)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.CharField(blank=True, max_length=250)),
                ('verrou_actif', models.BooleanField(default=True, editable=False, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.livre')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reservee_le'],
                'indexes': [models.Index(fields=['client', 'statut'], name='reservation_client__948f54_idx'), models.Index(fields=['livre', 'statut'], name='reservation_livre_i_704cf6_idx'), models.Index(fields=['statut', 'expire_le'], name='reservation_statut_exp_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'livre', 'verrou_actif'), name='reservation_active_unique'), models.CheckConstraint(condition=models.Q(('expire_le__gt', models.F('reservee_le'))), name='reservation_expiration_apres_creation'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'ACTIVE'), ('verrou_actif', True)), models.Q(models.Q(('statut', 'ACTIVE'), _negated=True), ('verrou_actif__isnull', True)), _connector='OR'), name='reservation_verrou_coherent'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'CANCELLED'), _negated=True), ('annulee_le__isnull', False), _connector='OR'), name='reservation_annulation_datee'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'REFUSED'), _negated=True), models.Q(('traitee_le__isnull', False), ('traitee_par__isnull', False)), _connector='OR'), name='reservation_refus_trace')],
            },
        ),
    ]
