# Generated by Django 5.2.15 on 2026-06-20 14:18

import accounts.managers
import accounts.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('cin', models.CharField(max_length=13, unique=True, validators=[accounts.validators.valider_cin], verbose_name='CIN')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('LIBRARIAN', 'Bibliothécaire'), ('CLIENT', 'Client')], db_index=True, default='CLIENT', max_length=12)),
                ('niveau_alerte', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score_risque', models.PositiveSmallIntegerField(default=0)),
                ('est_bloque', models.BooleanField(db_index=True, default=False)),
                ('deux_facteurs_actif', models.BooleanField(default=False)),
                ('notifications_email', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'verbose_name': 'administrateur',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', accounts.managers.AdministrateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
            ],
            options={
                'verbose_name': 'bibliothécaire',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', accounts.managers.BibliothecaireManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'client',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', accounts.managers.ClientManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='Smart Library EMSI', max_length=150)),
                ('duree_pret_jours', models.PositiveSmallIntegerField(default=15)),
                ('livres_max_par_client', models.PositiveSmallIntegerField(default=5)),
                ('penalite_par_jour', models.DecimalField(decimal_places=2, default=0.5, max_digits=8)),
                ('penalite_dommage', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('penalite_perte', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('delai_grace_jours', models.PositiveSmallIntegerField(default=2)),
                ('expiration_reservation_jours', models.PositiveSmallIntegerField(default=3)),
                ('alertes_retard', models.BooleanField(default=True)),
                ('resume_hebdomadaire', models.BooleanField(default=True)),
                ('duree_session_minutes', models.PositiveIntegerField(default=60)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration de la bibliothèque',
                'constraints': [models.CheckConstraint(condition=models.Q(('duree_pret_jours__gte', 1)), name='config_duree_pret_positive'), models.CheckConstraint(condition=models.Q(('livres_max_par_client__gte', 1)), name='config_quota_livres_positif'), models.CheckConstraint(condition=models.Q(('penalite_par_jour__gte', 0)), name='config_penalite_jour_positive'), models.CheckConstraint(condition=models.Q(('penalite_dommage__gte', 0)), name='config_penalite_dommage_positive'), models.CheckConstraint(condition=models.Q(('penalite_perte__gte', 0)), name='config_penalite_perte_positive'), models.CheckConstraint(condition=models.Q(('expiration_reservation_jours__gte', 1)), name='config_expiration_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'LIBRARIAN', 'CLIENT'])), name='utilisateur_role_valide'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(('score_risque__lte', 100)), name='utilisateur_risque_max_100'),
        ),
    ]
