# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('cible_type', models.CharField(max_length=100)),
                ('cible_id', models.CharField(max_length=80)),
                ('description_cible', models.CharField(blank=True, max_length=250)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['action', 'cree_le'], name='audit_action_date_idx'), models.Index(fields=['acteur', 'cree_le'], name='audit_acteur_date_idx'), models.Index(fields=['cible_type', 'cible_id'], name='audit_cible_idx')],
            },
        ),
    ]
