# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SYSTEM', 'Système'), ('RESERVATION', 'Réservation'), ('LOAN', 'Emprunt'), ('RETURN', 'Retour'), ('PENALTY', 'Pénalité'), ('SECURITY', 'Sécurité')], default='SYSTEM', max_length=15)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=250)),
                ('creee_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lue_le', models.DateTimeField(blank=True, null=True)),
                ('journal_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_generees', to='audit.journalaudit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creee_le'],
                'indexes': [models.Index(fields=['utilisateur', 'lue_le'], name='notification_user_lue_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type', 'SYSTEM'), ('journal_audit__isnull', False), _connector='OR'), name='notification_metier_auditee')],
            },
        ),
    ]
