# Generated by Django 5.2.15 on 2026-06-20 14:18

import catalog.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('biographie', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('nom',), name='auteur_nom_unique')],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_index=True, max_length=220)),
                ('isbn', models.CharField(max_length=17, unique=True, validators=[catalog.validators.valider_isbn])),
                ('description', models.TextField()),
                ('annee_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('editeur', models.CharField(blank=True, max_length=150)),
                ('poids_reference_grammes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tolerance_poids_grammes', models.PositiveSmallIntegerField(default=15)),
                ('code_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('couverture', models.ImageField(blank=True, upload_to='couvertures/')),
                ('visible_client', models.BooleanField(db_index=True, default=False, help_text='Limite le catalogue client aux ouvrages sélectionnés sans masquer le livre au personnel.')),
                ('stock_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_disponible', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('UNAVAILABLE', 'Indisponible'), ('MAINTENANCE', 'En maintenance')], db_index=True, default='AVAILABLE', max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteurs', models.ManyToManyField(related_name='livres', to='catalog.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livres', to='catalog.categorie')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('texte', models.TextField(max_length=1500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modere', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='catalog.livre')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='livre',
            constraint=models.CheckConstraint(condition=models.Q(('stock_total__gte', 1)), name='livre_stock_total_positif'),
        ),
        migrations.AddConstraint(
            model_name='livre',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__gte', 0)), name='livre_stock_disponible_positif'),
        ),
        migrations.AddConstraint(
            model_name='livre',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__lte', models.F('stock_total'))), name='livre_stock_disponible_valide'),
        ),
        migrations.AddConstraint(
            model_name='commentaire',
            constraint=models.UniqueConstraint(fields=('client', 'livre'), name='avis_unique_par_client_livre'),
        ),
    ]
