# Generated by Django 5.2.15 on 2026-06-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunte_le', models.DateField()),
                ('retour_prevu_le', models.DateField(db_index=True)),
                ('retourne_le', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'En cours'), ('RETURNED', 'Retourné'), ('INSPECTION', 'En inspection')], db_index=True, default='ACTIVE', max_length=12)),
                ('etat_retour', models.CharField(blank=True, choices=[('GOOD', 'Bon état'), ('DAMAGED', 'Endommagé'), ('LOST', 'Perdu')], max_length=10)),
                ('poids_retour_grammes', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire_retour', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='catalog.livre')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprunt', to='reservations.reservation')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-emprunte_le', '-id'],
                'indexes': [models.Index(fields=['client', 'statut'], name='loans_empru_client__1e96f2_idx'), models.Index(fields=['livre', 'statut'], name='loans_empru_livre_i_c0e0a4_idx'), models.Index(fields=['statut', 'retour_prevu_le'], name='emprunt_statut_echeance_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retour_prevu_le__gte', models.F('emprunte_le'))), name='emprunt_echeance_valide'), models.CheckConstraint(condition=models.Q(('retourne_le__isnull', True), ('retourne_le__gte', models.F('emprunte_le')), _connector='OR'), name='emprunt_retour_apres_debut'), models.CheckConstraint(condition=models.Q(models.Q(('statut', 'RETURNED'), _negated=True), ('retourne_le__isnull', False), _connector='OR'), name='emprunt_termine_date_retour')],
            },
        ),
    ]
